name: Pull request
on:
  push:
    branches:
      - "feat/*" # Support wildcard matching

# jobs:
#   pull-request:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: pull-request
#         uses: repo-sync/pull-request@v2
#         with:
#           destination_repository: "jhinning/sync-repo2"
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           source_branch: "" # If blank, default: triggered branch
#           destination_branch: "develop" # If blank, default: master
#           pr_title: "Pulling ${{ github.ref }} into dev" # Title of pull request
#           pr_body: | # Full markdown support, requires pr_title to be set
#             :crown: *An automated PR*

#             _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - uses: repo-sync/github-sync@v2
      #   name: Sync repo to branch
      #   with:
      #     source_repo: "jhinning/sync-repo2"
      #     source_branch: "develop"
      #     destination_branch: "repo-sync"
      #     github_token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: "jhinning/sync-repo1"
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.PAT_TOKEN }}
          destination_repository: "jhinning/sync-repo2" #<- You can also do this but not necessary
